language: java
sudo: true
jdk:
- oraclejdk8
after_success:
- bin/install-binaries
- mvn clean install -DskipTests=true
- mkdir -p deploy/target
- cp target/db-dumper-service-1.0.0.war deploy/target
- cp manifest.yml deploy/
- zip -r db-dumper-service ./deploy/*
deploy:
  provider: releases
  api_key:
    secure: dfICg3fWHErwHuuFTl7d1emJN8Tg0oK7/PLBmBf2QjGlY0CBOwX/y4O78kyJO2dYzD2Qiz08jqOB+Ff2v0MK11S0p/VfHn005Ys5uV6gDu/VwzjFxpiwTDTRF55Bbv3Izpv7+5TZkJb3pnG5UqNWjxpUmOfECUTaP5hggi2UP7pkpiQ90A3dZNSh6bsAx2lWlcaSe7FCBZigQ2PGuZ1TVIxLT2eIwkDhj61dk6hTALr01Rr5zpLI2WBMByQaeRco11gFgRYZ3Q2mSGMXIvmGqf7uUEnpCflqOOj54oGOLZEdtNGhl6r1JQmjl2a5NNWAE8mjDggi3N7XJBLl9d552z1r/cnn+/aaCgS7SOl1KiQvhe0yd9o8kdpmJC0PmY5WagkY6PQ98hh+8K/q5X8BE/x2m2A1UXhnLKAHFXpcJmU2EuaL68F5vLST7j+nSr4ClgRhYE+6NOlruFcELdfSB7sQbIlnoS+o8PYNxD94r88KAQT5d6FIdbFTs48f7aLRpTcCa3WnfKukCR/s7NL1HK3P2pPhaF5uL9XcrIejTzgPFU3SSs4CPQmUKn1jzLM9334gNLpRB2EYeMWdeBuZmBGWZ4FdzebUeGosHExBZkPonXZzIP6f+m3/oW2omp1O86MEEWAZu/2jDGIDgNL4YfxGOcHjGkVw4WHkeoZs5sc=
  file: db-dumper-service.zip
  on:
    repo: Orange-OpenSource/db-dumper-service
    tags: true
    all_branches: true