language: java
sudo: true
jdk:
- oraclejdk8
after_success:
- "mvn clean test jacoco:report"
- curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >t.jar
- java -jar t.jar -u init
- rm t.jar
- export PATH=$PATH:$HOME/jpm/bin
- jpm install com.codacy:codacy-coverage-reporter:assembly
- codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml
- mkdir go
- export GOPATH=$(pwd)/go
- bin/install-binaries
- mvn clean install -DskipTests=true
- mkdir -p db-dumper-service/target
- cp target/db-dumper-service-1.2.0.war db-dumper-service/target
- cp manifest.yml db-dumper-service/
- zip -r db-dumper-service ./db-dumper-service/*
deploy:
  provider: releases
  api_key:
    secure: dfICg3fWHErwHuuFTl7d1emJN8Tg0oK7/PLBmBf2QjGlY0CBOwX/y4O78kyJO2dYzD2Qiz08jqOB+Ff2v0MK11S0p/VfHn005Ys5uV6gDu/VwzjFxpiwTDTRF55Bbv3Izpv7+5TZkJb3pnG5UqNWjxpUmOfECUTaP5hggi2UP7pkpiQ90A3dZNSh6bsAx2lWlcaSe7FCBZigQ2PGuZ1TVIxLT2eIwkDhj61dk6hTALr01Rr5zpLI2WBMByQaeRco11gFgRYZ3Q2mSGMXIvmGqf7uUEnpCflqOOj54oGOLZEdtNGhl6r1JQmjl2a5NNWAE8mjDggi3N7XJBLl9d552z1r/cnn+/aaCgS7SOl1KiQvhe0yd9o8kdpmJC0PmY5WagkY6PQ98hh+8K/q5X8BE/x2m2A1UXhnLKAHFXpcJmU2EuaL68F5vLST7j+nSr4ClgRhYE+6NOlruFcELdfSB7sQbIlnoS+o8PYNxD94r88KAQT5d6FIdbFTs48f7aLRpTcCa3WnfKukCR/s7NL1HK3P2pPhaF5uL9XcrIejTzgPFU3SSs4CPQmUKn1jzLM9334gNLpRB2EYeMWdeBuZmBGWZ4FdzebUeGosHExBZkPonXZzIP6f+m3/oW2omp1O86MEEWAZu/2jDGIDgNL4YfxGOcHjGkVw4WHkeoZs5sc=
  file: db-dumper-service.zip
  on:
    repo: Orange-OpenSource/db-dumper-service
    tags: true
    all_branches: true
env:
  global:
    secure: pNZZlgQ2eKNWeCrvb9M0HcoBmxUJAKB/SlZc8W9L8zZfZDQWbufrsfPATVzRqTECyU7EK+3reM9JOLKIiXf3XKf/wp4/NiH7xcC3otAqD/btsoYcQ9W2vAZVcml4XbNdyWAoCPSOySUZqtvYe4Ou+f3+3JHKxaNBH2hDvN9iQFDkOyaf05KAQ8G6DA3xk0L2u/A27EAqsM0ZiSD9pcI1UscQVg6Xkja0KkxmRVJORMppuqH6PhOWxYeIJQ9VhOvti0I52iVE5es9AVO8eJdsWxNDAQxiaHz/VR/BIrFmxZMf79ys320sp0M9McOuflV4IsWo6MxG+E4txzGg3j7CbO5TwniljlQ92j7A/a3omOVhxn/868U75fD5YrYL16Deqmfiem26oEGmEWFiYwuFKlO77dVO7sGacqDd1mrtY73dYILtX8kYHGLcsuHX8aTFB1wTTPCqEMuUdtq+RjNkZ6T7KeIn/Z5AN4cqRAJwsf4yg3bHbhplDnAzw6K8FMWZulFS1l8wMiS+z+7J7Zhk2BQTGeJA0uzzcXrkZNlhpm6u2UuZHIZdhsL82DftSMKXgecrY6dV6zlUxc9qoyZjFNeq+gDBsNhlTyFgYgePLC88GtHHcsLN8FGVI1oNg0ruRWEmQ4FN9G4Taf4TfEzwpPaHYNmzq7sYbcMQ/xjRXrE=
