language: java
sudo: true
jdk:
- oraclejdk8
services:
- mysql
- postgresql
- mongodb
- redis-server
before_script:
- mysql -e 'create database dbdumpertestsource;'
- mysql -e 'create database dbdumpertesttarget;'
- psql -c 'create database dbdumpertestsource;' -U postgres
- psql -c 'create database dbdumpertesttarget;' -U postgres
install:
- mkdir go
- export GOPATH=$(pwd)/go
- bin/install-binaries
script:
- mvn -B clean verify -P all-tests jacoco:report
after_success:
- curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >t.jar
- java -jar t.jar -u init
- rm t.jar
- export PATH=$PATH:$HOME/jpm/bin
- jpm install com.codacy:codacy-coverage-reporter:assembly
- codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml
- mvn -B clean install -DskipTests=true
- mkdir -p db-dumper-service/target
- cp target/db-dumper-service-1.2.0.war db-dumper-service/target
- cp manifest.yml db-dumper-service/
- zip -r db-dumper-service ./db-dumper-service/*
deploy:
  provider: releases
  api_key:
    secure: dfICg3fWHErwHuuFTl7d1emJN8Tg0oK7/PLBmBf2QjGlY0CBOwX/y4O78kyJO2dYzD2Qiz08jqOB+Ff2v0MK11S0p/VfHn005Ys5uV6gDu/VwzjFxpiwTDTRF55Bbv3Izpv7+5TZkJb3pnG5UqNWjxpUmOfECUTaP5hggi2UP7pkpiQ90A3dZNSh6bsAx2lWlcaSe7FCBZigQ2PGuZ1TVIxLT2eIwkDhj61dk6hTALr01Rr5zpLI2WBMByQaeRco11gFgRYZ3Q2mSGMXIvmGqf7uUEnpCflqOOj54oGOLZEdtNGhl6r1JQmjl2a5NNWAE8mjDggi3N7XJBLl9d552z1r/cnn+/aaCgS7SOl1KiQvhe0yd9o8kdpmJC0PmY5WagkY6PQ98hh+8K/q5X8BE/x2m2A1UXhnLKAHFXpcJmU2EuaL68F5vLST7j+nSr4ClgRhYE+6NOlruFcELdfSB7sQbIlnoS+o8PYNxD94r88KAQT5d6FIdbFTs48f7aLRpTcCa3WnfKukCR/s7NL1HK3P2pPhaF5uL9XcrIejTzgPFU3SSs4CPQmUKn1jzLM9334gNLpRB2EYeMWdeBuZmBGWZ4FdzebUeGosHExBZkPonXZzIP6f+m3/oW2omp1O86MEEWAZu/2jDGIDgNL4YfxGOcHjGkVw4WHkeoZs5sc=
  file: db-dumper-service.zip
  on:
    repo: Orange-OpenSource/db-dumper-service
    tags: true
    all_branches: true
env:
  global:
  - secure: pNZZlgQ2eKNWeCrvb9M0HcoBmxUJAKB/SlZc8W9L8zZfZDQWbufrsfPATVzRqTECyU7EK+3reM9JOLKIiXf3XKf/wp4/NiH7xcC3otAqD/btsoYcQ9W2vAZVcml4XbNdyWAoCPSOySUZqtvYe4Ou+f3+3JHKxaNBH2hDvN9iQFDkOyaf05KAQ8G6DA3xk0L2u/A27EAqsM0ZiSD9pcI1UscQVg6Xkja0KkxmRVJORMppuqH6PhOWxYeIJQ9VhOvti0I52iVE5es9AVO8eJdsWxNDAQxiaHz/VR/BIrFmxZMf79ys320sp0M9McOuflV4IsWo6MxG+E4txzGg3j7CbO5TwniljlQ92j7A/a3omOVhxn/868U75fD5YrYL16Deqmfiem26oEGmEWFiYwuFKlO77dVO7sGacqDd1mrtY73dYILtX8kYHGLcsuHX8aTFB1wTTPCqEMuUdtq+RjNkZ6T7KeIn/Z5AN4cqRAJwsf4yg3bHbhplDnAzw6K8FMWZulFS1l8wMiS+z+7J7Zhk2BQTGeJA0uzzcXrkZNlhpm6u2UuZHIZdhsL82DftSMKXgecrY6dV6zlUxc9qoyZjFNeq+gDBsNhlTyFgYgePLC88GtHHcsLN8FGVI1oNg0ruRWEmQ4FN9G4Taf4TfEzwpPaHYNmzq7sYbcMQ/xjRXrE=
  - secure: C9xfqnDafUjpGKlfAnwUTiS6zarLPMyFPjxCeusWDcRnMMACgKfy3ELo1Z+/4f1veIsLtFXrOTOk6RwWoPbVoVbZa5l6jF96AGtxIMgQtKDS0DrwlibaSnviN4YGJ4oIs627Md7eZ5KLQajTaDM2mxYt+MKJlGq/1GuUcoNUwW/wyM/hSISS4uxpMQ03VeHdJcYIg8nnH1VVrJKqgUPYarLIayMPyraDtVxjC1+Kt/Lxqo1xly53YbKAwhubh+x1ZAOZskLOjYxQBuM43GfbzKSaGdq3Tjs8Wb+Bk+vyD/ceUjf1iCpvDLBP7T8D5HHT5Q1W5q8O9ZVNgH9eY4dpxe/h1EBk1QS8DHd4vY+2githP/lLZLRTg8tUcYV7HpPi1x8JOlG8zFVx++/N+G4zzULqtZ2+bInC7FEeUX/61wByJrBGpRO7n0/ZWR1OKnJwxS3Iszduh+zvSg24Hnf4c/gBnqptXNWTPOSNWgeqwm+s90tF/O6txLS6cnxenwwUC4xurSdpV/UwoWxHGkqLyjTgfj8S3TEuDdAW3/2tsPDy4M41zP9rzA0+C8WU6jtsiTJBB8Gjm4/nY5u19jzWW1nEnSC5QkvAzDg2yDKYShRv5Jj4Mvq1iQ1MzG/O+R+scsEZ/5gHfOB9CQhtnwUDIW33pd6vlvK40lWivgnFWig=
  - secure: PRlkd21OHQ27Ku3kukjE2k9ukBy/9A6Gmd9E4UW8EBtny8y1rVXHCVBGmajYJsOOPdA/KUm6+fTbJRjdCp0idvXyqz8TluQfklGihby6zK8PvqYnmcsPD89pbbxziFPp4VbquQUVRb2Nd4b7mPBWmXcvIeQB9dUQlxIyWvpjW42O+9a4fKT9VQ5ZfiuHkNikqVEXmW9vw6QKhv1DXuaqVhdRNKiHrnecZZpH6YuxPO9NaWmSts1vijcEOuslOUMIlxXcFOsbwv5FMy+fStxu43bihZgno9a61EGyG+BCplr4X+yP1fb0djxFL/zwh1I1o9fRhDaH/WfkwxL/YXB11LHnlhfMReQF7ZHVV3zS7FK0abCMZ+3748MEOJtVpHdZ04XK8NggjRwcbGtlFTPeUHCCv5rvJo3lBShXwxdTtNbWYV99+xKaEPE4RzBcDuWz6IRZyEeiXwV/JEi91pyY2YnrA/u9nTSCgILLBLEtiGdpQ2IA5BlYI7UvPxMpyrIgffzIYWQ4DQMuHp3z6wIiPcZVoGxUDypj/vRMD3XINmibcc7prF6tDBOxKMuz+JZlep0I615TUERLqqxOWp6Eko+sDa569U+1EjoN9t/DQmuuI5fWNhrypS0jaMCNDD8oAYylr5RQO/anCAvDpaVgP3+MeIH5uZpoipWZz+JBhuk=
  - test_cf_admin_org=bercheg-org
  - test_cf_admin_space=int-db-dumper
  - cloud_controller_url=https://api.run.pivotal.io
  - int_cf_service_name_mongodb=skipped-cause-mongolab-have-issue
  - int_cf_service_name_redis=blocked-cause-of-pws
