logging.level.com.orange.clara.cloud.servicedbdumper: INFO

---
show.command.line: false
endpoints:
  env:
    keys-to-sanitize: jdbcurl,uri,DATABASE_URL,username,url,password,key_id,access_key,VCAP_SERVICES,encryption_key
management:
  contextPath: /admin
spring:
  boot:
    admin:
      client:
        service-url: http://${vcap.application.uris[0]:localhost:8080}
        name: db-dumper-service-${vcap.application.instance_id:1}
  jpa:
    hibernate:
      ddl-auto: none
app:
  maven:
    version: @project.version@
security:
  require-ssl: ${use.ssl:false}
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: ${uaa_url:http://fake.uaa.com}/oauth/token
      userAuthorizationUri: ${uaa_url:http://fake.uaa.com}/oauth/authorize
      clientAuthenticationScheme: header
      scope:
      - openid
      - cloud_controller_service_permissions.read
    resource:
      userInfoUri: ${uaa_url:http://fake.uaa.com}/userinfo
      preferTokenInfo: false
