logging.level.com.orange.clara.cloud.servicedbdumper: INFO
---
management:
  contextPath: /admin
spring:
  jpa:
    hibernate:
      ddl-auto: none
security:
  user:
    password: none
  oauth2:
    client:
      clientId: your-client-id-uaa
      clientSecret: your-client-secret-uaa
      accessTokenUri: http://cf.uaa.url/oauth/token
      userAuthorizationUri: http://cf.uaa.url/oauth/authorize
      clientAuthenticationScheme: header
      scope:
      - openid
      - cloud_controller.read
      - cloud_controller.write
    resource:
      userInfoUri: http://cf.uaa.url/userinfo
      preferTokenInfo: false
