logging.level.com.orange.clara.cloud.servicedbdumper: INFO

---
endpoints:
  env:
    keys-to-sanitize: jdbcurl,uri,DATABASE_URL,username,url,password,key_id,access_key,VCAP_SERVICES
management:
  contextPath: /admin
spring:
  boot:
    admin:
      client:
        service-url: http://${vcap.application.uris[0]:localhost:8080}
        name: db-dumper-service-${vcap.application.instance_id:1}
  jpa:
    hibernate:
      ddl-auto: none
security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: ${CF_TARGET:http://fake.uaa.com}/oauth/token
      userAuthorizationUri: ${CF_TARGET:http://fake.uaa.com}/oauth/authorize
      clientAuthenticationScheme: header
      scope:
      - openid
    resource:
      userInfoUri: ${CF_TARGET:http://fake.uaa.com}/userinfo
      preferTokenInfo: false
