resources:
  - name: db-dumper-service
    type: git
    source:
      uri: https://github.com/Orange-OpenSource/db-dumper-service.git
      branch: master
  - name: db-dumper-travis
    type: travis
    source:
      repository: Orange-OpenSource/db-dumper-service
      github-token: {{github_token}}
      branch: master
resource_types:
- name: travis
  type: docker-image
  source:
    repository: orangeopensource/travis-resource-image
jobs:

  - name: db-dumper-tests
    plan:
      - get: db-dumper-service
      - get: db-dumper-travis
        params:
          download-logs: true
      - task: see-travis-logs
        file: db-dumper-service/pipelines/ci/see-logs-task.yml

  - name: db-dumper-accept-1mb
    plan:
      - get: db-dumper-travis
        trigger: true
        passed: [db-dumper-tests]
      - get: db-dumper-service
      - task: accept
        params:
          cloud_controller_url: {{cloud_controller_url}}
          accept_cf_service_name_mysql: {{service_mysql}}
          accept_cf_service_plan_mysql: {{service_plan_mysql}}
          accept_cf_service_name_postgresql: {{service_postgresql}}
          accept_cf_service_plan_postgresql: {{service_plan_postgresql}}
          accept_cf_service_name_mongodb: skipped-mongo
          accept_cf_service_name_redis: skipped-redis
          test_cf_admin_org: {{test_cf_admin_org}}
          test_cf_admin_space: {{test_cf_admin_space}}
          cf_admin_user: {{cf_admin_user}}
          cf_admin_password: {{cf_admin_password}}
          show_command_line: true
          DYNO: true # remove it to not run integration test on s3
          S3_URL: {{s3_url}}
          test_accept_file_size: 1Mb
          test_timeout_creating_service: {{test_timeout_creating_service}}
          test_timeout_action: {{test_timeout_action}}
        file: db-dumper-service/pipelines/ci/acceptance-task.yml
