resources:
  - name: db-dumper-service
    type: git
    source:
      uri: https://github.com/Orange-OpenSource/db-dumper-service.git
      branch: master
jobs:
  - name: db-dumper-unit
    plan:
      - get: db-dumper-service
      - task: unit
        file: pipelines/ci/unit-task.yml