resources:
  - name: db-dumper-service
    type: git
    source:
      uri: https://github.com/Orange-OpenSource/db-dumper-service.git
      branch: master
  - name: db-dumper-concourse-image
    type: docker-image
    source:
      email: {{docker-hub-email}}
      username: {{docker-hub-username}}
      password: {{docker-hub-password}}
      repository: {{docker-hub-image}}
jobs:
  - name: db-dumper-unit
    plan:
      - get: db-dumper-service
        trigger: true
      - task: unit
        file: db-dumper-service/pipelines/ci/unit-task.yml

  - name: db-dumper-integration
    plan:
      - get: db-dumper-service
        trigger: true
        passed: [db-dumper-unit, publish-db-dumper-concourse]
      - task: integration
        params:
          cloud_controller_url: {{cloud_controller_url}}
          int_cf_service_name_mongodb: skipped-cause-mongolab-have-issue
          test_cf_admin_org: {{test_cf_admin_org}}
          test_cf_admin_space: {{test_cf_admin_space}}
          cf_admin_user: {{cf_admin_user}}
          cf_admin_password: {{cf_admin_password}}
        file: db-dumper-service/pipelines/ci/integration-task.yml

  - name: publish-db-dumper-concourse
    public: true
    serial: true
    plan:
    - get: db-dumper-service
      trigger: true
    - put: db-dumper-concourse-image
      params:
        build: db-dumper-service/pipelines/dockerfiles

groups:
- name: tests
  jobs:
  - db-dumper-unit
  - db-dumper-integration
- name: docker-image
  jobs:
  - publish-db-dumper-concourse