resources:
  - name: db-dumper-service
    type: git
    source:
      uri: https://github.com/Orange-OpenSource/db-dumper-service.git
      branch: master
jobs:
  - name: db-dumper-unit
    plan:
      - get: db-dumper-service
        trigger: true
      - task: unit
        file: db-dumper-service/pipelines/ci/unit-task.yml

  - name: db-dumper-integration
    plan:
      - get: db-dumper-service
        trigger: true
        passed: [db-dumper-unit]
      - task: integration
        params:
          cloud_controller_url: {{cloud_controller_url}}
          int_cf_service_name_mongodb: skipped-cause-mongolab-have-issue
          test_cf_admin_org: {{test_cf_admin_org}}
          test_cf_admin_space: {{test_cf_admin_space}}
          cf_admin_user: {{cf_admin_user}}
          cf_admin_password: {{cf_admin_password}}
          DYNO: true # remove it to not run integration test on s3
          S3_URL: {{s3_url}}
        file: db-dumper-service/pipelines/ci/integration-task.yml

  - name: db-dumper-accept-100mb
    plan:
      - get: db-dumper-service
        trigger: true
        passed: [db-dumper-integration]
      - task: say-hello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: orangeopensource/db-dumper-concourse
              tag: 'latest'
          run:
            path: echo
            args: ["Hello, world!"]

